\c recipes_dev;

INSERT INTO recipes (dish, category, ingredients, prep_time, cook_time, total_time, directions, nutrition_facts, tips, is_good, is_quick, image_url) VALUES (
    'Tortilla Scrambled Egg & Cheese',
    'Breakfast',
    '1 large egg, 1 teaspoon milk, 1 1/2 teaspoons butter, 1 flour tortilla, 2 slices jalapeno pepper jack cheese', 
    '4 minutes', 
    '6 minutes', 
    '10 minutes', 
    'Step 1: Whisk egg and milk together in a small bowl. Step 2: Melt butter in a skillet over medium heat. Pour in egg mixture and tilt skillet until egg covers the skillet. Cook until egg is set, about 2 minutes. Place flour tortilla over egg, and carefully flip egg and tortilla so that the tortilla is now on the bottom. Step 3: Place cheese slices over egg. Cook until tortilla is crisp, 3 to 4 minutes. Cover skillet and cook until cheese is melted, 1 to 2 minutes', 
    1767,
    null, 
    TRUE, 
    TRUE, 
    'https://www.tasteofhome.com/wp-content/uploads/2018/01/Southwest-Tortilla-Scramble_exps163395_TH132104C06_21_5b_RMS-5.jpg?fit=700%2C1024'),

('Lentil Soup','Dinner','1/4 cup olive oil, 1 onion - chopped, 2 carrots - diced, 2 stalks celery - chopped, 2 cloves garlic - minced, 1 bay leaf, 1 teaspoon dried basil, 2 cups dry lentils, 8 cups water, 1 can crushed tomatoes, 1/2 cup spinach - sliced thin, 2 tablespoons vinegar, salt/ground black pepper to taste', '15 minutes', '1 hour 20 minutes', '1 hour 35 minutes', 
'Step 1: Heat oil in large soup pot over medium heat. Add onions, carrots, and celery; cook and stir until onion is tender. Step 2: Stir in garlic, bay leaf, oregano, and basil; cook for 2 minutes. Step 3: Stir in lentils, and add water and tomatoes. Bring to boil. Reduce heat and let simmer until lentils are tender, at least 1 hour. Step 4: Stir in spinach and cook until it wilts. Step 5: Stir in vinegar and season with salt and pepper.', 349, 'Serve with warm cornbread', TRUE, FALSE, 'https://www.eatingonadime.com/wp-content/uploads/2021/11/ip-lentil-soup-6-2.jpg'),

('California Club Chicken Wraps','Lunch','1/2 cup mayo, 1/2 cup plain yogurt, 2 chipotle chiles, 2 spinach tortillas, 1/2 cup shredded lettuce, 1 1/2 cups shredded Monterey Jack cheese, 1 avocado - peeled and diced, 4 slices cooked bacon, 1 red onion - finely chopped, 1 tomato - chopped, 2 cooked chicken breasts - cut into chunks', '15 minutes', '1 minutes', '16 minutes', 
'Step 1: Whisk mayonnaise, yogurt, and chipotle chiles together in a bowl. Step 2: Cook tortillas in the microwave until warm and pliable, about 30 seconds. Step 3: Spread 1 tablespoon chipotle mayo down the center of each tortilla. Spread 1/2 of  the Monterey Jack cheese, 1/2 of the avocado, 1/2 of the bacon, 1/2 the red onion, 1/2 tomato, and 1/2 of the chicken in the center of the tortilla. Fold opposite edges of tortilla to overlap the filling. Roll 1 of the opposite edges around the filling into a wrap.', 1462, 'Place wrap in a panini maker for 1 to 2 minutes, or until wrap has grill marks.Try with chipotle ranch sauce. 1/2 cup ranch dressing for mayo to make ranch sauce', TRUE, TRUE, 'https://i2.wp.com/thequickerkitchen.com/wp-content/uploads/2023/07/California-Club-Chicken-Wrap-3.jpg'),

('Pastrami Reuben Sandwich','Lunch','3/4 cup Thousand Island dressing, 8 slices rye bread, 16 ounce can sauerkraut - drained, 8 slices Swiss cheese, 8 slices pastrami, 1/4 cup margarine - softened', '10 minutes', '10 minutes', '20 minutes', 
'Step 1: Spread dressing onto one side of each bread slice. op 1/2 of the slices with sauerkraut, SWISS cheese, and pastrami, then top with remaining bread, dressing-side down. Spread margarine on the outside of each sandwich. Step 2: Heat large skillet over medium-high heat. Grill sandwiches until bread is golden brown, fillings are hot, and cheese is melted, 3 to 5 minutes per side.', 793, 'Serve with coleslaw', TRUE, TRUE, 'https://izzycooking.com/wp-content/uploads/2021/09/Pastrami-Sandwich-1.jpg'),

('Peanut Butter Oatmeal','Breakfast','1 cup milk, 1 teaspoon fine sugar, 1 pinch salt, 1 pinch cinnamon, 1/2 cup of oats, 1/2 teaspoon vanilla extract, 1 tablespoon peanut butter, 2 teaspoons warmed honey, 1 tablespoon chopped walnuts', '5 minutes', '5 minutes', '10 minutes', 
'Step 1: Combine milk, sugar, and salt in a saucepan over medium-low heat and bring to simmer. Step 2: Add cinnamon and oats. Cook over medium-low heat until oats are tender with a bite. Adjust heat to prevent splattering. Step 3: Remove from heat, stir in vanilla and peanut butter. Serve in large bowl top with honey and walnuts', 449, null, TRUE, TRUE, 'https://www.spoonfulofflavor.com/wp-content/uploads/2021/10/peanut-butter-banana-oatmeal-recipe.jpg'),

('Spaghetti Sauce w/Ground Beef','Dinner','1 pound ground beef, 1 medium onion - chopped, 4 cloves of garlic - minced, 1 small green bell pepper - diced, 28 ounce can diced tomatoes, 16 ounce can tomato paste, 2 teaspoons dried oregano, 2 teaspoons dried basil, 1 teaspoon salt, 1/2 teaspoon ground black pepper', '10 minutes', '1 hour 5 minutes', '1 hour 15 minutes', 
'Step 1: Combine ground beef, onion, garlic, and green pepper in large saucepan over medium-high heat. Cook and stir until meat is browned and crumble and vegetables are tender, 5 to 7 minutes. Drain grease. Step 2: Stir diced tomatoes, tomato sauce, an tomato paste into the pan. Season with oregano, basil, salt, and pepper. Simmer spaghetti sauce for 1 hour, stirring occasionally. Step 3: Serve hot', 185, 'Pour sauce over cooked spaghetti and top with Parmesan cheese', TRUE, FALSE, 'https://www.cookerru.com/wp-content/uploads/2022/12/spaghetti-meat-sauce-3-web-1170x1755.jpg.webp'),

('Baked Mac n Cheese with Chicken Meatballs','Dinner','6 cups of water, 1 box macaroni and cheese mix, 1/4 cup milk, 1/4 cup margarine, 1 1/2 cups shredded sharp Cheddar cheese, 1/3 cup chopped onion, 1 jalapeno - seeded and chopped, 1 egg - beaten, 1 teaspoon garlic powder, 1 teaspoon onion powder, 1 teaspoon paprika, 1 pound pre-cooked chicken meatballs - thawed, 1/4 cup panko bread crumbs','15 minutes', '30 minutes', '45 minutes', 
'Step 1: Bring water to a boil in a saucepan. Add macaroni and cook until tender, 7 to 8 minutes; drain. Stir in margarine, milk, and cheese sauce packet. Let cool. Step 2: Preheat oven to 400 degrees F(200C). Grease a 9 inch baking dish. Step 3: Stir together prepared mac and cheese, Cheddar cheese, onions, jalapeno, egg, garlic powder, onion powder, and paprika until well combined. Stir in meatballs. Pour macaroni mixture into the prepared dish. Top with bread crumbs. Step 4: Bake in preheated oven until golden brown about 20 minutes.', 617, 'Top with barbeque sauce and serve with baked garlic bread', TRUE, FALSE, 'https://theviewfromgreatisland.com/wp-content/uploads/2023/01/meatball-mac-and-cheese-8567-January-07-2023-2.jpg'),

('Perfect Pancakes','Breakfast','2 cups milk, 1/4 cup white vinegar, 2 1/2 cups flour, 3/4 cup sugar, 2 teaspoon baking powder, 1 teaspoon baking soda, 1 teaspoon salt, 3 large eggs, 1 teaspoon vanilla extract, softened butter for greasing', '5 minutes', '20 minutes', '25 minutes', 
'Step 1: Preheat a griddle to 300 degrees F (175C). Step 2: Stir together milk and vinegar in a small bowl. Step 3: Whisk together flour, sugar, baking powder, baking soda, and salt in second bowl. Step 4: Beat eggs in large bowl until smooth. Add vanilla and milk mixture; whisk together. Add flour mixture to bowl with egg mixture and whisk until combined. If batter is lumpy, let rest 3 minutes and stir again. Step 5: Melt some butter on the griddle, don''t over-grease. Spoon batter in 1/3 cup portions onto griddle. Cook until bubbles form on surface of batter, about 2 minutes. Step 6: Flip pancakes and cook until browned on the other side, about 1 1/2 minutes more. Repeat with remaining batter. Serve immediately with butter.', 1767, 'Up the ante with toppings such as sprinkles, chopped chocolate, or sliced fruit',TRUE, FALSE, 'https://static.onecms.io/wp-content/uploads/sites/43/2022/02/16/21014-Good-old-Fashioned-Pancakes-mfs_001.jpg'),

('Kimchi Chicken Melt Sandwich','Lunch', '1/2 cup shredded cooked chicken, 2 tablespoons Kimchi, 2 tablespoons mayonnaise, 1 tablespoon softened butter, 2 slices bread, 2 slices Provolone cheese, 2 slices Havarti cheese', '5 minutes', '5 minutes', '10 minutes', 
'Step 1: Combine shredded chicken, kimchi, and mayo in small bowl. Step 2: Preheat small skillet over medium-heat. Spread 1/2 tablespoon butter n one side of slice of bread. Place 1 slice bread butter-side-down in skillet, place 1 slice provolone and 1 slice Havarti cheese onto bread. Top with chicken mixture, the with remaining cheeses. Butter second bread slice on one side and place butter-side-up on top of sandwich. Step 3: Cook until bread is lightly browned and flip over, about 2 minutes per side', 810, null, TRUE, TRUE, 'https://cdn.scrambledchefs.com/wp-content/uploads/2016/03/Kimchi-Sandwich-_-Scrambled-Chefs-5.gif'),

('Chicken Cordon Bleu','Dinner','nonstick cooking spray, 4 skinless, boneless chicken breast halves, 1/4 teaspoon salt, 1/8 teaspoon ground black pepper, 6 slices Swiss cheese, 4 slices cooked ham, 1/2 cup seasoned bread crumbs', '10 minutes', '35 minutes', '45 minutes', 
'Step 1: Preheat oven to 350 degrees F (175 degrees C). Coat a 7x11-inch baking dish with nonstick cooking spray. Step 2: Pound chicken breasts to 1/4 inch thickness. Step 3: Sprinkle each piece of chicken on both sides with salt and pepper. Place 1 Swiss cheese slice and 1 ham slice on top of each breast. Step 4: Roll up each breast and secure with toothpicks. Step 5: Place in the prepared baking dish and sprinkle chicken evenly with bread crumbs. Step 6: Bake in the preheated oven until chicken is no longer pink, 30 to 35 minutes. Step 7: Remove from the oven, and place 1/2 Swiss cheese slice on top of each breast. Step 8: Return to the oven until cheese has melted, 3 to 5 minutes. Remove toothpicks and serve immediately.', 419, null, TRUE, FALSE, 'https://www.cookingclassy.com/wp-content/uploads/2022/12/chicken-cordon-bleu-4.jpg'),

('Garlic Chili Oil Noodles','Lunch','1 pack ramen noodles, 2 teaspoons sesame oil, 2 teaspoons soy sauce, 1 tablespoon chiu chow style chili oil, 4 cloves garlic - minced, 1 pinch black sesame seeds, 2 green onions - sliced.', '5 minutes', '5 minutes', '10 minutes', 
'Step 1: Bring a pot of water to a boil. Add ramen noodles, and cook until tender, 3 to 4 minutes. Step 2: Meanwhile, heat sesame oil, soy sauce, and chili oil in a wok over medium-high heat. Step 3: Add garlic and stir fry until fragrant, 30 to 45 seconds. Remove from heat. Drain ramen noodles, add to the wok, and toss to coat. Sprinkle with sesame seeds and scallions.', 616, null,  TRUE, TRUE, 'https://www.chilitochoc.com/wp-content/uploads/2022/11/chili-oil-noodles-with-garlic-and-green-onion.jpg'),

('Honey Glazed Chicken','Dinner', '1/4 cup honey, 2 tablespoons soy sauce, 1/8 teaspoons red pepper flakes, 1 1/2 tablespoons olive oil, 2 skinless, boneless chicken breast halves, cut into bite-size pieces', '10 minutes', '10 minutes', '20 minutes', 
'Step 1: Whisk honey, soy sauce, and red pepper flakes in a bowl. Set aside. Step 2: Heat olive oil in skillet; cook and stir until chicken is no longer pink in the center and sauce is thickened, about 5 minutes.', 179, 'Pair with brown rice and black beans', TRUE, FALSE, 'https://bigoven-res.cloudinary.com/image/upload/t_recipe-1280/honey-glazed-chicken-6d46dd.jpg'),

('Grilled Cheese Sandwich','Lunch', '4 slices wheat bread, 3 tablespoons butter, 2 slices Cheddar cheese', '5 minutes', '10 minutes', '15 minutes', 
'Step 1: Preheat a nonstick skillet over medium heat. Generously butter one side of a slice of bread. Place bread butter-side down in the hot skillet; add 1 slice of cheese. Butter a second slice of bread on one side and place butter-side up on top of cheese. Step 2: Cook until lightly browned on one side; flip over and continue cooking until cheese is melted. Repeat with remaining 2 slices of bread, butter, and slice of cheese.', 400, 'Pair this with homemade tomato soup.', TRUE, TRUE, 'https://www.thisisnotdietfood.com/wp-content/uploads/2021/04/garlicbreadgrilledcheese-03square-735x735.jpg'),

('Simple Macaroni and Cheese','Lunch', '1 box elbow macaroni, 1/4 cup butter, 1/4 cupp all-purpose flour, 1/2 teaspoon salt, ground black pepper to taste, 2 cups milk, 2 cups shredded Cheddar cheese', '10 minutes', '15 minutes', '25 minutes', 
'Step 1: Cook elbow macaroni a boiling water, stirring until cooked through but firm to the bite, 8 minutes. Step 2: At the same time, melt butter in a saucepan. Step 3: Add flour, salt, and pepper and stir until smooth, about 5 minutes. Step 4: Pour in milk slowly, while stirring. Continue to cook and stir until mixture is smooth and bubbling, about 5 minutes. Step 5: Add Cheddar cheese and stir until melted. Step 6: Drain macaroni and fold into chesses sauce until coated.', 630, null, TRUE, FALSE, 'https://www.thecookierookie.com/wp-content/uploads/2013/12/15-minute-macaroni-cheese-9-of-9.jpg'),

('Korean Ground Beef Bowl','Dinner', '1 pound ground beef, 5 cloves garlic - crushed, 1 tablespoon grated ginger, 2 teaspoons sesame oil, 1/2 cup reduce sodium soy sauce, 1/3 cup light brown sugar, 1/4 teaspoon crushed red pepper, 6 green onions - chopped, 4 cups hot cooked brown rice, 1 tablespoon sesame seeds', '10 minutes', '15 minutes', '25 minutes', 
'Step 1: Heat large skillet over medium-high heat. Add beef and cook, stirring until beef is crumbling into small browned pieces. Drain excess grease. Step 2: Stir in garlic, ginger, and sesame oil and cook until fragrant, about 2 minutes. Stir in sou sauce, brown sugar, and red pepper. Cook until beef absorbs some sauce, about 7 minutes. Add 1/2 of chopped green onions. Step 3: Serve over hot cooked rice and garnish with sesame seeds and remaining green onions', 574, null, TRUE, FALSE, 'https://thebusybaker.ca/wp-content/uploads/2018/04/easy-korean-beef-rice-bowls-fbig2.jpg'),

('Breakfast Vegetable Scramble','Breakfast', '2 tablespoons olive oil, 1/2 red onion, 1 red bell pepper or orange, 4 cups baby kale or spinach, 1 tablespoon chopped chives, 4 eggs, 1/4 cup shredded Colby cheese, 1/4 teaspoon salt, black pepper, avocado slices for serving', '8 minutes', '7 minutes', '15 minutes', 
'Step 1: Thinly slice the red onion, large dice the bell pepper. Step 2: In medium bowl, whisk eggs, stir in shredded cheese, fresh herbs, salt, and black pepper. Step 3: Heat olive oil in large skillet over medium-high heat. Add the onion and peppers, cook 3 to 4 minutes until tender and just starting to brown. Reduce heat. Add a pinch of salt and the baby greens. Cook for 30 seconds until wilted. Remove from heat and set aside. Step 4: Keep heat low, cook eggs for 20 to 30 seconds. Use flat spatula to scrape sections of eggs, gently stirring until cooked. Step 5: Add vegetables, stir for a few seconds and serve.', 360, 'Eggs may be substituted with Tofu', TRUE, TRUE, 'https://www.acouplecooks.com/wp-content/uploads/2020/09/Veggie-Breakfast-Scramble-008.jpg'),

('Grilled Tomahawk Steak','Dinner', 'Steak Rub & Steak: 1 tablespoon brown sugar, 1 tablespoon Montreal steak seasoning, 2 teaspoons garlic powder, 2 teaspoons onion powder, 1 tomahawk steak. Compound Butter: 1/4 cup salted butter, 1 tablespoon minced shallot, 1 clove garlic - minced, 1 tablespoon chopped chives, 2 teaspoons steak rub.', '15 minutes', '50 minutes', '13 hrs 15 minutes', 
'Step 1: Steak rub: place brown sugar, steak seasoning, garlic powder, and onion powder in a small airtight container; shake to combine. Set aside 2 teaspoons steak rub to use in compound butter. Step 2: Place steak on a half sheet pan and rub the steak rub until well coated on all sides. Place steak, uncovered, in the refrigerator to dry-brine overnight. Step 3: Compound butter: place butter, shallot, garlic, chives, and reserved steak rub in a small bowl. Mash together with fork until evenly combined. Spoon butter into small airtight container, cover, refrigerate until use. Step 4: Remove steak from refrigerator 1 hour before cooking to take the chill off. It will cook in the same sheet used for dry-brining. Step 5: Preheat oven to 300F(150C). Step 6: Bake steak on the sheet pan and use digital meat thermometer, bake until thermometer  reads 125F(51C), Step 7: Remove steak at specified temperature and smear with compound butter. Let steak rest for 10 minutes. Step 8: Slice and serve.', 649, 'Serve on a platter of baked rice, and a chopped wedge salad with blue cheese dressing.', TRUE, FALSE, 'https://www.mychicagosteak.com/steak-university/wp-content/uploads/2021/12/cooked-tomahawk-steak-in-cast-iron-skillet-1.jpg'), 

('Frito Chicken Casserole','Dinner', '1 tablespoon unsalted butter, 1 small onion, 4 cups cubed cooked chicken breast, 1 can black beans - rinsed and drained, 1 can corn - drained, 1 can condensed cream of chicken soup, 1 can diced tomatoes and green chiles - undrained, 1 can chopped green chilies, 1 package cream cheese, 1/3 cup chopped cilantro, 2 cups shredded Cheddar cheese, 1 bag chili and cheese flavored corn chips', '10 minutes', '40 minutes', '1 hour 20 minutes', 
'Step 1: Preheat oven to 350F(175C). Step 2: Melt butter in large saucepan over medium heat, add onion and cook until softened, about 5 minutes. Step 3: Add chicken, beans, corn, cream of chicken soup, tomatoes and chiles with juice, green chiles, cream cheese, and cilantro. Cook until cream cheese has melted. Step 4: Spread out 1/3 of the chips on the bottom of rectangular casserole dish. Top with 1/2 chicken mixture. Top chicken with 1/3 shredded Cheddar cheese. Repeat the layer. Top 2nd layer with remaining 1/3 chips and 1/3 cheese. Step 5: Bake in preheated oven until cheese melted and is lightly browned. Step 6: Remove from oven and let sit for 30 minutes before serving', 479, 'Serve with salsa and sour cream', TRUE, FALSE, 'https://hollishomestead.com/wp-content/uploads/2021/03/Frito-Casserole-15-600x400.jpg'), 

('Brown Sugar Meatloaf w/Ketchup Glaze','Dinner','1/2 cup ketchup, 1/2 cup packed brown sugar, 1 1/2 teaspoons salt, 1/2 teaspoon chili powder, 1 1/2 pounds ground beef, 1 1/2 cups croutons - crushed, 1 small onion - chopped, 2 eggs, 1/4 cup milk, 1/4 teaspoon black pepper', '20 minutes', '1 hour', '1 hour 20 minutes', 
'Step 1: Preheat oven to 350F(175C). Lightly grease a loaf pan. Step 2: Stir ketchup, brown sugar, salt, and chili powder together in a bowl until smooth. Spread a small amount of ketchup mixture into the bottom of the greased loaf pan. Step 3: Mix ground beef, croutons, onion, eggs, milk, and black pepper together in a large bowl; shape into a loaf and put into prepared pan. Spread remaining ketchup mixture over loaf. Step 4: Bake until no longer pink in the center, about 1 hour. ', 793, 'Serve with coleslaw', TRUE, FALSE, 'https://img.hellofresh.com/f_auto,fl_lossy,q_auto,w_1200/hellofresh_s3/image/brown-sugar-bourbon-pork-meatloaves-c9abebee.jpg');



-- //psql -U postgres -f db/schema.sql;
-- //psql -U postgres -f db/seed.sql;



